# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ios' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!


  pod 'KUI', :path => './UI/'


  # Pods for ios

  target 'iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
